config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'welcome#index'
  resources :materials
  resources :purchases, only: %i[index show new create]
  resources :orders, only: %i[index show new create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ApplicationRecord
  has_many :purchase_items, dependent: :restrict_with_exception
  has_many :purchases, through: :purchase_items
  has_many :order_items, dependent: :restrict_with_exception
  has_many :orders, through: :order_items
  
  paginates_per 10
  
  scope :for_title, ->(title) { where(["title LIKE ?", "%#{title}%"]) }
  validates :title, presence: true, uniqueness: true
  validates :quantity, numericality: { greater_than_or_equal_to: 0}
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :materials, through: :order_items

  accepts_nested_attributes_for :order_items, allow_destroy: true

  paginates_per 5
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :material
  belongs_to :order
  before_save :check_inventory
  after_save :create_log
  validates :quantity, numericality: { greater_than_or_equal_to: 0}
  validate :is_business_hour?, :is_weekend?, :is_enough?

  def check_inventory
    material = Material.find(material_id)
    return if is_business_hour?
    return if is_weekend?
    return if is_enough?
    material.quantity -= quantity
    material.save!
  end

  def is_business_hour?
    errors.add(:created_at, I18n.t("order_item.business_hour")) if Time.now.hour >= 17 || Time.now.hour < 9
  end

  def is_weekend?
    errors.add(:created_at, I18n.t("order_item.weekend")) if Date.today.saturday? || Date.today.sunday?
  end

  def is_enough?
    if quantity?
      errors.add(:quantity, I18n.t("order_item.enough_quantity")) if self.material.quantity < quantity
    end
  end

  def create_log
    file_name = "#{Date.today.strftime("%d-%m-%Y")}-log.txt"
    File.open("log/#{file_name}", 'a') do |f|
      f.write("Saída feita por #{self.order.user.email} em #{created_at.strftime("%d-%m-%Y às %H:%M:%S")} - Material: #{material.title} - Quantidade: #{quantity} \n")
    end
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :user
  has_many :purchase_items
  has_many :materials, through: :purchase_items

  accepts_nested_attributes_for :purchase_items, allow_destroy: true

  paginates_per 5
end

app/models/purchase_item.rb
class PurchaseItem < ApplicationRecord
  belongs_to :material
  belongs_to :purchase
  before_save :check_inventory
  after_save :create_log
  
  validates :quantity, numericality: { greater_than_or_equal_to: 0}

  def check_inventory
    material = Material.find(material_id)
    material.quantity += quantity 
    material.save!
  end

  def create_log
    file_name = "#{Date.today.strftime("%d-%m-%Y")}-log.txt"
    File.open("log/#{file_name}", 'a') do |f|
      f.write("Entrada feita por #{self.purchase.user.email} em #{created_at.strftime("%d-%m-%Y às %H:%M:%S")} - Material: #{material.title} - Quantidade: #{quantity} \n")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :rememberable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: %i[show edit destroy update]

  def index
    @materials = Material.page(params[:page])
    title_field = params[:title]
    if title_field.present?
      @materials = Material.for_title(title_field).page(params[:page])
    end
  end

  def new
    @material = Material.new
    respond_to do |format|
      format.html 
      format.js
    end
  end

  def create
    @material = Material.new(material_params)
    if @material.save
      redirect_to materials_path, notice: 'material was successfully created'
    else
      render :new
    end
  end

  def show; end
  def edit; end

  def update
    if @material.update(material_params)
      redirect_to materials_path, notice: 'material was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    begin
      @material.destroy
      redirect_to materials_path, notice: 'material was successfully destroyed'
    rescue ActiveRecord::DeleteRestrictionError
      flash[:error] = 'material was not destroyed'
      redirect_to materials_path
    end
  end

  private

  def set_material
    @material = Material.find(params[:id])
  end

  def material_params
    params.require(:material).permit(:title, :quantity)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_materials, only: %i[create new]
  def index
    @orders = Order.page(params[:page])
  end

  def new
    @materials = Material.all
    @order = Order.new
    @order.order_items.build
  end

  def show
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save
      redirect_to materials_path, notice: 'Order was successfully created'
    else 
      render :new
    end
  end

  private

  def order_params
    params.require(:order).permit(order_items_attributes: [:id, :material_id, :quantity, :order_id, :_destroy])
  end

  def check_quantity
    @material = Material.find(params[:order][:order_items_attributes]["0"][:material_id])
    quantity = (params[:order][:order_items_attributes]["0"][:quantity]).to_s
    render :new, flash[:error]= "Quantity is not enough " if @material.quantity.to_s < quantity
  end

  def set_materials
    @materials = Material.all
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_materials, only: %i[create new]
  def index
    @purchases = Purchase.page(params[:page])
  end

  def new
    
    @purchase = Purchase.new
    @purchase.purchase_items.build

    respond_to do |format|
      format.html 
      format.js
    end
  end

  def show
    @purchase = Purchase.find(params[:id])
  end

  def create
    @purchase = Purchase.new(purchase_params)
    @purchase.user = current_user
    if @purchase.save
      redirect_to purchases_path, notice: 'Purchase was successfully created'
    else
      render :new
    end
  end

  private

  def purchase_params
    params.require(:purchase).permit(purchase_items_attributes: [:id, :material_id, :quantity, :purchase_id, :_destroy])
  end
  def set_materials
    @materials = Material.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    purchases = Purchase.all
    orders = Order.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)

    case level
    when "alert"
         "alert alert-warning alert-dismissible fade show"
    when "notice"     
         "alert alert-success alert-dismissible fade show"
    when "error" 
         "alert alert-danger alert-dismissible fade show"
    else
         "alert alert-primary alert-dismissible fade show"
    end
  end
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('Inventory Manager') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "shared/navigation" %>
      
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>" role="alert">
              <%= value %>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/materials/_form.html.erb
<% material.errors.each do |key, value| %>
<div class="<%= flash_class('error') %>" role="alert">
  <%= t("#{key}") %> <%= value %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>
<%= form_with model: material do |form| %>
  <div class="form-group">
    <%= form.label :title %>  
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :quantity %>  
    <%= form.text_field :quantity , class: "form-control" %>
  </div>
  <div class="mt-2">  
    <%= form.submit t("send"), class: "btn btn-primary" %>
  </div>
<% end %>

<div class="pt-3">
  <%= link_to t('back'), materials_path %>
</div>

app/views/materials/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-bs-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel">Adicionando Material</h4>
</div>
<div class="modal-body">
  <h1><%= t('new') %> material</h1>

  <%= render 'form', material: @material %>
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/materials/edit.html.erb
<section class="py-5">
  <h1><%= t('edit') %> material</h1>

  <%= render 'form', material: @material %>
</section>

app/views/materials/index.html.erb
<section class="py-3">
  <%= form_tag(materials_path, method: :get) do %>
  <div class="form-group mt-3 col-sm-10">
    Search by title: 
      <%= text_field_tag(:title) %>
      <%= submit_tag("Search") %>
    <% end %>
  </div>
  
  <br>
  <table class="table">
    <th>ID</th>
    <th><%= t('Title') %></th>
    <th><%= t('Quantity') %></th> 
    <th colspan="3"> <%= link_to 'Adicionar material', new_material_path,  {:remote => true, 'data-bs-toggle' =>  "modal", 'data-bs-target' => '#modal-window', class: 'btn btn-primary btn-lg'}  %>
      <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content"></div>
        </div>
      </div></th> 
  <% if @materials.count() > 0%>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.id %></td>
        <td><%= material.title %></td>
        <td><%= material.quantity %></td>
        <td > <%= link_to t('edit'), edit_material_path(material) , 
        class: 'btn btn-warning' %></td>
        <td > <%= link_to t('show'), material_path(material),
          class: 'btn btn-info'  %> </td>
        <td > <%= link_to t('delete'), material_path(material), 
          method: :delete, data: { confirm: 'Você está certo disso ?' }, 
          class: 'btn btn-danger'%> </td>
      </tr>
    <% end %>
    <% else %>
      <tr class="text-align center">No materials yet.</tr>
    <% end %>
  </table>
  
    
  <div class="row">
    <div class="text-center">
      <%= paginate @materials %>
    </div>  
    
</section>

app/views/materials/new.html.erb
<section class="py-5">
  <h1><%= t('new') %> material</h1>

  <%= render 'form', material: @material %>
</section>

app/views/materials/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/materials/show.html.erb
<div class="row d-flex justify-content-center mt-5 ">
  <div class="col-md-6">
    <div class="card" style="width: 18rem;">
      <div class="card-body">
        <h5 class="card-title"><%= @material.title %></h5>
        <p class="card-text">Quantity: <%= @material.quantity %></p>
      </div>
    </div>
  </div>
  <div class="col-3-md">
    <%= link_to t('back'), materials_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/orders/_order_item_fields.html.erb
<div class="nested-fields">
  <div class="form-group col-md-3">
    <%= f.label :quantity %>
    <%= f.text_field :quantity, class: 'form-control' %>
  </div>
  
  <div class="form-group col-md-5">
    <%= f.label :material_id %>
    <%= f.collection_select(:material_id, @materials, :id, :title, include_blank: false, class: 'form-control' ) %>
  </div>
  
  <div>
    <%= link_to_remove_association t("remove order item"), f %>
  </div>
  
</div>

app/views/orders/index.html.erb
<section class="py-3">
  <table class="table">
    <th><%= t('Order Date') %></th>
    <th><%= t('Client') %></th>
    <th><%= t('Detail') %></th>
    <th colspan="3"> <%= link_to "#{t('new')} #{t('Order')}", new_order_path, 
      class: 'btn btn-success' %></th> 
    <% @orders.each do |order| %>
    <tr>
      <td><%= order.created_at.strftime('%d/%m/%Y') %></td>
      <td><%= order.user.email %></td>
      <td > <%= link_to t('show'), order_path(order),
        class: 'btn btn-info'  %> </td>
    </tr>
    <% end %>
  </table>
  
  <div class="text-center">
    <%= paginate @orders %>
  </div>  
</section>

app/views/orders/new.html.erb
<section class="py-5">
  <h1><%= t('new') %> Order</h1>

  <% @order.errors.each do |value| %>
  <div class="<%= flash_class('error') %>" role="alert">
    <%= value.message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
  <%= form_with model: @order do |order_form| %>
    
    <h2>Materials</h2>
    
    <div id="order_items">
      <%= order_form.fields_for :order_items do |order_items_form| %>
        <div class="form-group">
          <%= render "order_item_fields", f: order_items_form %>
        </div>
      <% end %>

      <div class="links">
        <%= link_to_add_association t('add order items'), order_form, :order_items %>
      </div>
    </div>
    <br />
    <%= order_form.submit t('create'),class: "btn btn-primary" %>
  <% end %>
</section>

app/views/orders/show.html.erb
<section class="py-5">
  <h5>
    A saída foi realizada pelo: <%= @order.user.email %> em <%= @order.created_at.strftime("%d-%m-%Y às %H:%M:%S") %>
  </h5>
  <div class="row d-flex justify-content-center mt-5 ">
    <% @order.order_items.each do |order_item| %>
      <div class="col-md-4">
        <div class="card text-white bg-success mb-3 " style="max-width: 18rem;">
          <div class="card-header text-center"><%= order_item.material.title %></div>
          <div class="card-body">
            <h3 class="card-title">Saídas: <%= order_item.quantity %></h3>
            <h6 class="card-title">Quantidade atual em estoque: <%= order_item.material.quantity %></h6>
          </div>
        </div>
      </div>
    <% end %>

<br>
<br>
</div>
<div class="col-md-6 mt-5">
  <%= link_to t('back'), orders_path, class: "btn btn-primary" %>
</div>
</section>

app/views/purchases/_form.html.erb
<section class="py-5">
  <% @purchase.errors.each do |value| %>
  <div class="<%= flash_class('error') %>" role="alert">
    <%= value.message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  <% end %>
  <%= form_with model: @purchase do |purchase_form| %>
    
    <h2>Materials</h2>
    
    <div id="purchase_items">
      <%= purchase_form.fields_for :purchase_items do |purchase_items_form| %>
        <div class="form-group">
          <%= render "purchase_item_fields", f: purchase_items_form %>
        </div>
      <% end %>

      <div class="links">
        <%= link_to_add_association t('add purchase items'), purchase_form, :purchase_items %>
      </div>
    </div>
    <br />
    <%= purchase_form.submit t('create'),class: "btn btn-primary" %>
  <% end %>
</section>

app/views/purchases/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-bs-dismiss="modal">x</button>
  <h4 class="modal-title" id="myModalLabel"><%= t('create') %> Purchase </h4>
</div>
<div class="modal-body">
  <%= render 'form', purchase: @purchase %>
</div>
<div class="modal-footer">
  <button class="btn btn-primary">Save</button>
</div>

app/views/purchases/_purchase_item_fields.html.erb
<div class="nested-fields">
  <div class="form-group col-md-3">
    <%= f.label :quantity %>
    <%= f.text_field :quantity, class: 'form-control' %>
  </div>
  
  <div class="form-group col-md-5">
    <%= f.label :material_id %>
    <%= f.collection_select(:material_id, @materials, :id, :title, include_blank: false, class: 'form-control' ) %>
  </div>
  
  <div>
    <%= link_to_remove_association t("remove purchase item"), f %>
  </div>
  
</div>

app/views/purchases/index.html.erb
<section class="py-3">
  <table class="table">
    <th><%= t('Purchase Date') %></th>
    <th><%= t('Client') %></th>
    <th><%= t('Detail') %></th>
    <th colspan="3"> <%= link_to "#{t('new')} #{t('Purchase')}", new_purchase_path, 
      class: 'btn btn-success' %></th> 
    <% @purchases.each do |purchase| %>
    <tr>
      <td><%= purchase.created_at.strftime('%d/%m/%Y') %></td>
      <td><%= purchase.user.email %></td>
      <td > <%= link_to t('show'), purchase_path(purchase),
        class: 'btn btn-info'  %> </td>
    </tr>
    <% end %>
  </table>
  
  <div class="text-center">
    <%= paginate @purchases %>
  </div>
</section>

app/views/purchases/new.html.erb
<section class="py-5">
  <h1><%= t('new') %> Purchase</h1>

  <%= render 'form', purchase: @purchase %>
</section>

app/views/purchases/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal();

app/views/purchases/show.html.erb
<section class="py-5">
  <h5>
    A entrada foi realizada por: <%= @purchase.user.email %> em <%= @purchase.created_at.strftime("%d-%m-%Y às %H:%M:%S") %>
  </h5>
  <div class="row d-flex justify-content-center mt-5 ">
    <% @purchase.purchase_items.each do |purchase_item| %>
      <div class="col-md-4">
        <div class="card text-white bg-success mb-3 " style="max-width: 18rem;">
          <div class="card-header text-center"><%= purchase_item.material.title %></div>
          <div class="card-body">
            <h3 class="card-title">Entrada: <%= purchase_item.quantity %></h3>
            <h6 class="card-title">Quantidade atual em estoque: <%= purchase_item.material.quantity %></h6>
          </div>
        </div>
      </div>
    <% end %>

<br>
<br>
</div>
<div class="col-md-6 mt-5">
  <%= link_to t('back'), purchases_path, class: "btn btn-primary" %>
</div>
</section>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <%= link_to t('Inventory Manager'), root_path, 
        class: "navbar-brand" %>     
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <% if current_user %>
                    <li class="nav-item">
                        <%= link_to t('My Materials'), materials_path, 
                        class: "dropdown-item" %>     
                    </li>

                    <li class="nav-item">
                        <%= link_to t('My Purchases'), purchases_path, 
                        class: "dropdown-item" %>     
                    </li>

                    <li class="nav-item">
                        <%= link_to t('My Orders'), orders_path, 
                        class: "dropdown-item" %>     
                    </li>
                <% end %>
                
            </ul>
            <% if current_user %> 
                <ul class="navbar-nav">
                    
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                            
                            <%= current_user.email %> 
                        
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            
                            <li>
                                <%= link_to t('edit'),edit_user_registration_path(current_user), class: "dropdown-item" %>
                            </li>
                            <li><hr class="dropdown-divider" /></li>
                            <li>
                                <%= link_to t('logout'),destroy_user_session_path,method: :delete, class: "dropdown-item" %>
                            </li>
                    </li>
                </ul>
                <% else %>
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <%= link_to 'Login', new_user_session_path, class: "dropdown-item" %>
                    </li>
                </ul>
            <% end %>
        </div>
    </div>
</nav>

app/views/welcome/index.html.erb
<section class="py-5">
  <div class="row d-flex justify-content-center ">
    <div class="col-md-3">
      <div class="card text-white bg-warning mb-3 " style="max-width: 18rem;">
        <div class="card-header text-center"><%= link_to 'Materiais', materials_path, class: "text-white", style: "text-decoration: none; font-size: 28px; font-weight: bold;" %></div>
        <div class="card-body">
          <h3 class="card-title">Materiais Cadastrados: <%= Material.count %></h3>
        </div>
      </div>
    </div>
    <div class="col-md-3">
      <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
        <div class="card-header text-center"> <%= link_to 'Entradas', purchases_path, class: "text-white" , style: "text-decoration: none; font-size: 28px; font-weight: bold;" %></div>
        <div class="card-body">
          <h3 class="card-title">Entradas Cadastradas: <%= Purchase.count %></h3>
        </div>
      </div>  
    </div>
    <div class="col-md-3">
      <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
        <div class="card-header text-center"><%= link_to 'Saídas', orders_path, class: "text-white" , style: "text-decoration: none; font-size: 28px; font-weight: bold;"%></div>
        <div class="card-body">
          <h3 class="card-title">Saídas Cadastradas: <%= Order.count %></h3>
        </div>
      </div>
    </div>
    
    
  </div>
  
</section>